//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTDUtilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICTDUtilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_Utilities_icon_csd {
            get {
                object obj = ResourceManager.GetObject("_1_Utilities_icon_csd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_Utilities_icon_csd_2 {
            get {
                object obj = ResourceManager.GetObject("_1_Utilities_icon_csd_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CsdObjScanning.accdb.
        /// </summary>
        internal static string dbName {
            get {
                return ResourceManager.GetString("dbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\svmain\db$\ReportsPrinting.
        /// </summary>
        internal static string dbServerPath {
            get {
                return ResourceManager.GetString("dbServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:\dbs\WAEC\ICTD\DBs.
        /// </summary>
        internal static string dbServerPathLocal {
            get {
                return ResourceManager.GetString("dbServerPathLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deletered16x16 {
            get {
                object obj = ResourceManager.GetObject("Deletered16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap header_890x100_no_background {
            get {
                object obj = ResourceManager.GetObject("header_890x100_no_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap header_890x100_no_background_flag {
            get {
                object obj = ResourceManager.GetObject("header_890x100_no_background_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string minShadedTotal {
            get {
                return ResourceManager.GetString("minShadedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ok16x16 {
            get {
                object obj = ResourceManager.GetObject("Ok16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OkRoundGreen16x16 {
            get {
                object obj = ResourceManager.GetObject("OkRoundGreen16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlaceHolderFemale {
            get {
                object obj = ResourceManager.GetObject("PlaceHolderFemale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlaceHolderMale {
            get {
                object obj = ResourceManager.GetObject("PlaceHolderMale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap POWER___STANDBY {
            get {
                object obj = ResourceManager.GetObject("POWER___STANDBY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PRINTER {
            get {
                object obj = ResourceManager.GetObject("PRINTER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\svictd03.waec.gm\Scan Files\Current Year.
        /// </summary>
        internal static string scannedObjSavePath {
            get {
                return ResourceManager.GetString("scannedObjSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:\dbs\WAEC\ictd\DBs.
        /// </summary>
        internal static string scannedObjSavePathLocal {
            get {
                return ResourceManager.GetString("scannedObjSavePathLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string subjectLength {
            get {
                return ResourceManager.GetString("subjectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\svictd03.waec.gm\icd\DBs\Scan Files.
        /// </summary>
        internal static string textFileBackupPath {
            get {
                return ResourceManager.GetString("textFileBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\WAEC\\Backup\\Scan Files.
        /// </summary>
        internal static string textFileBackupPathLocal {
            get {
                return ResourceManager.GetString("textFileBackupPathLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap waec_logo_big {
            get {
                object obj = ResourceManager.GetObject("waec_logo_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waec_Logo_Big_washout_20_50 {
            get {
                object obj = ResourceManager.GetObject("Waec_Logo_Big_washout_20_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WAEC_LOGO_soft_bevel {
            get {
                object obj = ResourceManager.GetObject("WAEC_LOGO_soft_bevel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WAEC_LOGO_soft_bevel1 {
            get {
                object obj = ResourceManager.GetObject("WAEC_LOGO_soft_bevel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\svictd03.waec.gm\Exams Pictures\WASSCESC.
        /// </summary>
        internal static string WassceSCPicturePath {
            get {
                return ResourceManager.GetString("WassceSCPicturePath", resourceCulture);
            }
        }
    }
}
