//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsPrinting.Models
{
    using System;
    
    public partial class ExamReports
    {
        public string ExamID { get; set; }
        public string ExamName { get; set; }
        public int ExamInitial { get; set; }
        public string ExamShortName { get; set; }
        public int ExamYear { get; set; }
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public bool ReportAvailable { get; set; }
        public string ReportViewName { get; set; }
        public string ReportSpName { get; set; }
        public System.DateTime TS { get; set; }
    }
}
