//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsPrinting.Models
{
    using System;
    
    public partial class Exam
    {
        public string ExamID { get; set; }
        public int ExamInitial { get; set; }
        public string ExamName { get; set; }
        public string ExamShortName { get; set; }
    }
}
