//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsPrinting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WaecCommonDBEntities : DbContext
    {
        public WaecCommonDBEntities()
            : base("name=WaecCommonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Centre> uspCentre_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Centre>("uspCentre_GetAll");
        }
    
        public virtual ObjectResult<Exam> uspExam_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Exam>("uspExam_GetAll");
        }
    
        public virtual ObjectResult<uspExamYears_GetAll_Result> uspExamYears_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspExamYears_GetAll_Result>("uspExamYears_GetAll");
        }
    
        public virtual ObjectResult<uspExamYears_GetByExamID_Result> uspExamYears_GetByExamID(string examId)
        {
            var examIdParameter = examId != null ?
                new ObjectParameter("ExamId", examId) :
                new ObjectParameter("ExamId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspExamYears_GetByExamID_Result>("uspExamYears_GetByExamID", examIdParameter);
        }
    
        public virtual ObjectResult<uspTimetable_GetByExamId_ExamYear_Result> uspTimetable_GetByExamId_ExamYear(string examID, Nullable<int> examYear)
        {
            var examIDParameter = examID != null ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(string));
    
            var examYearParameter = examYear.HasValue ?
                new ObjectParameter("ExamYear", examYear) :
                new ObjectParameter("ExamYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspTimetable_GetByExamId_ExamYear_Result>("uspTimetable_GetByExamId_ExamYear", examIDParameter, examYearParameter);
        }
    
        public virtual ObjectResult<ExamReports> uspExamReports_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExamReports>("uspExamReports_GetAll");
        }
    
        public virtual ObjectResult<uspExamReportsSp_GetByExamId_ExamYear_ReportID_Result> uspExamReportsSp_GetByExamId_ExamYear_ReportID(string examID, Nullable<int> examYear, Nullable<int> reportID)
        {
            var examIDParameter = examID != null ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(string));
    
            var examYearParameter = examYear.HasValue ?
                new ObjectParameter("ExamYear", examYear) :
                new ObjectParameter("ExamYear", typeof(int));
    
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspExamReportsSp_GetByExamId_ExamYear_ReportID_Result>("uspExamReportsSp_GetByExamId_ExamYear_ReportID", examIDParameter, examYearParameter, reportIDParameter);
        }
    }
}
