//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAT8Processing.Model
{
    using System;
    
    public partial class NatEntries
    {
        public string ExamID { get; set; }
        public string ExamName { get; set; }
        public int ExamInitial { get; set; }
        public string ExamShortName { get; set; }
        public int ExamYear { get; set; }
        public string CentreNumber { get; set; }
        public string IndexNumber { get; set; }
        public string CandidateName { get; set; }
        public int SexID { get; set; }
        public int DisabilityID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int Attempts { get; set; }
        public string CentreName { get; set; }
        public string SexName { get; set; }
        public string SexShortName { get; set; }
        public string DisabilityName { get; set; }
        public int RegionID { get; set; }
        public int AreaID { get; set; }
        public int LocationID { get; set; }
        public int SchoolTypeID { get; set; }
        public string RegionName { get; set; }
        public string AreaName { get; set; }
        public string LocationName { get; set; }
        public string SchoolType { get; set; }
        public Nullable<System.DateTime> CandidateEntryBegin { get; set; }
        public Nullable<System.DateTime> CandidateEntryEnd { get; set; }
    }
}
