//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAT8Processing.Model
{
    using System;
    
    public partial class ServerGetDateTime
    {
        public System.DateTime CurrentDate { get; set; }
        public Nullable<int> CurrentYear { get; set; }
        public Nullable<int> CurrentMonth { get; set; }
        public Nullable<int> currentDay { get; set; }
    }
}
